import dichotomy_trichotomy_solutions_ordinary_differential_theorem_canonical_lane_mathlib.GateLemmas
import dichotomy_trichotomy_solutions_ordinary_differential_theorem_canonical_lane_mathlib.FinalTheorem
